### ISSUE TITLE
Error installing on Windows  py3

### ISSUE THREAD

**Issue by angelqb17** [django-auth-ldap/django-auth-ldap#109]
I get the next error when i try to install:

    c:\users\dbasql\appdata\local\temp\pip-install-taezgy6a\python-ldap\modules\
constants.h(7): fatal error C1083: Cannot open include file: 'lber.h': No such f
ile or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Buil
dTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exi
t status 2

    ----------------------------------------
Command "e:\flujos\pyvenv\scripts\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\dbasql\\AppData\\Local\\Temp\\pip-install-taezgy6a\\python-
ldap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replac
e('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --recor
d C:\Users\dbasql\AppData\Local\Temp\pip-record-zcef9jbv\install-record.txt --si
ngle-version-externally-managed --compile --install-headers e:\flujos\pyvenv\inc
lude\site\python3.6\python-ldap" failed with error code 1 in C:\Users\dbasql\App
Data\Local\Temp\pip-install-taezgy6a\python-ldap\

Y got:

python 3.6.4
django 2.0.8

**Comment by angelqb17** [comment]
my solution was install the plugin with this method:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-ldap

**Comment by jdufresne** [comment]
This looks like the error is coming from python-ldap, not django-auth-ldap. The message "Cannot open include file: 'lber.h': No such file or directory" suggests the installation can't find openldap headers, which is not a bug in django-auth-ldap (or python-ldap) but a system issue.
