### ISSUE TITLE
When LDAP is misconfigured, stack traces contain user passwords in plain text

### ISSUE THREAD

**Issue by ben-kuhn** [django-auth-ldap/django-auth-ldap#114]
When LDAP is misconfigured, the stack trace, often sent to syslog and--in some projects--via email to the configured admins contains the users password in plain text.  This is an information disclosure vulnerability as users of the syslog or monitoring systems, email administrators, and anyone with access to read application logs access to users passwords in plain text.

If a server was compromised in some other way, the attacker could use this vulnerability to gather credentials, pivot, potentially escalate privileges, and move throughout the network.

If this were to happen accidentally, the user logging in and seeing the login failure may not know that their password was exposed to users with access to the various places the stack trace may be logged and not realize that their password would need to be changed.

Here is an obfuscated snippet from the email I received containing the full stack trace when I encountered this bug using NetBox:
```
Exception Type: ImproperlyConfigured at /login/
Exception Value: AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance.
Request information:
USER: AnonymousUser

GET: No GET data

POST:
csrfmiddlewaretoken = 'token'
next = '/'
username = 'myUserName'
password = 'myPasswordInPlainText'

FILES: No FILES data

COOKIES:
csrftoken = 'token'
```

### Environment
* Python version:  3.6.7
* NetBox version:  2.5.5

### Steps to Reproduce
1. Install NetBox from git
2. Configure Admins and Mail settings 
3. Configure Logging
4. Configure LDAP, but make a mistake somewhere so that authentication will not work
5. Attempt to log in.  Don't use a real password if this is a production environment

### Expected Behavior
Errors to be logged and potentially emailed with passwords hashed,obfuscated, or not included at all

### Actual Behavior
My LDAP password was emailed in plain text as part of the stack trace to the entire team, as well as logged in the log file locally and on the remote syslog server

**Comment by jdufresne** [comment]
Thanks for the report. This is certainly something to avoid.

This case looks like a bug with netbox. In their [`LoginView`](https://github.com/digitalocean/netbox/blob/57fecdbf173a6d611e9e9387fd6dd9cd8021d941/netbox/users/views.py#L23-L50), the `password` POST parameter has not been identified as a sensitive parameter. Please see the documentation for how to achieve this:

https://docs.djangoproject.com/en/2.1/howto/error-reporting/#django.views.decorators.debug.sensitive_post_parameters

If you still believe this is an issue with django-auth-ldap, please provide additional details.

**Comment by jdufresne** [comment]
For an example, see how Django uses `sensitive_post_parameters` for its login view:

https://github.com/django/django/blob/f63811f4813f0e0439e140a97eeba18a5017e858/django/contrib/auth/views.py#L38-L102

**Comment by ben-kuhn** [comment]
Thank you.  I originally reported this upstream to NetBox [Issue 2880](https://github.com/digitalocean/netbox/issues/2880).  I will update that issue with this information.

**Comment by jeremystretch** [comment]
Thanks @jdufresne, that was my mistake.

**Comment by hallcountymis** [comment]
Just to be clear, this is a netbox issue, not a django-auth-ldap issue, correct?

**Comment by mattburlage** [comment]
Just to be clear, this is a netbox issue only, correct?

**Comment by jeremystretch** [comment]
@mattburlage Correct.

**Comment by mattburlage** [comment]
Thank you.
