### ISSUE TITLE
Remove user when not present in LDAP anymore

### ISSUE THREAD

**Issue by t-book** [django-auth-ldap/django-auth-ldap#116]
Hi,

is there some way function that a created Django user is removed/disabled when it´s not present in LDAP anymore?

**Comment by jdufresne** [comment]
Do you mean at login time or at a regular interval without the user logging in?

Either way, no, this isn't' a supported feature. But there are enough pieces in place such that this should be doable for your Django application.

**Comment by t-book** [comment]
@jdufresne thanks a lot for your reply. I meant second. It would be nice to have some management command to 'sync' users. In case the user got deleted at LDAP side it could be set to inactive with Django. One could run this by cron or celery-beat. Most likely I would read all LDAP users and compare them with django users, right?

**Comment by jdufresne** [comment]
> Most likely I would read all LDAP users and compare them with django users, right?

Yes, this is exactly right. Depending on how many users are in either the database or directory, this could take a long time. If you'd like to submit a PR to create this management command I'll review it for potential inclusion.

**Comment by t-book** [comment]
Great thanks, I´ll dive into as soon there is time.
