### ISSUE TITLE
Support for Django 2.1

### ISSUE THREAD

**Issue by ryhoo2** [django-auth-ldap/django-auth-ldap#124]
After upgrading Django python module from 2.0.13 to 2.1 authentication stopped working - I get "Incorrect username or password" message. Unfortunately there's no debug logs coming along.
I looked through the [Release Notes](https://docs.djangoproject.com/en/2.2/releases/2.1/) of Django 2.1 but have no idea what might cause problem.
Any clues? Thanks!

**Comment by jdufresne** [comment]
I've been using Django 2.1 for some time with success. So I'm not sure. There is not enough information here to debug the issue. If you can provide minimal steps that I can use to reproduce, please let me know and we can reopen.

**Comment by ryhoo2** [comment]
Thanks for the feedback. I'll look in dependencies first.
