### ISSUE TITLE
Cryptography not found

### ISSUE THREAD

**Issue by Rubyj** [django-auth-ldap/django-auth-ldap#133]
@jdufresne 

Updating from 1.4 to 1.7 results in the following error when my server is started (not when using runserver, when using nginx/caddy)

`ModuleNotFoundError: No module named 'cryptography'`

**Comment by jdufresne** [comment]
Please provide a full stack trace

**Comment by Rubyj** [comment]
@jdufresne 

```
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/bin/daphne", line 6, in <module>
web_1      |     from daphne.cli import CommandLineInterface
web_1      |   File "/usr/lib/python3.6/site-packages/daphne/cli.py", line 11, in <module>
web_1      |     from .server import Server
web_1      |   File "/usr/lib/python3.6/site-packages/daphne/server.py", line 32, in <module>
web_1      |     from .ws_protocol import WebSocketFactory
web_1      |   File "/usr/lib/python3.6/site-packages/daphne/ws_protocol.py", line 6, in <module>
web_1      |     from autobahn.twisted.websocket import (
web_1      |   File "/usr/lib/python3.6/site-packages/autobahn/twisted/__init__.py", line 58, in <module>
web_1      |     from autobahn.twisted.wamp import ApplicationSession
web_1      |   File "/usr/lib/python3.6/site-packages/autobahn/twisted/wamp.py", line 50, in <module>
web_1      |     from autobahn.wamp import protocol, auth
web_1      |   File "/usr/lib/python3.6/site-packages/autobahn/wamp/auth.py", line 43, in <module>
web_1      |     from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
web_1      | ModuleNotFoundError: No module named 'cryptography'

```

the stack mentions daphne but this issue only happens after I bump the version from 1.4 of this plugin to something higher. Back at 1.4 it works just fine.

**Comment by jdufresne** [comment]
I don't see django-auth-ldap in that stack at all, so I'm not sure it is the fault of this package. It looks to me like `autobahn` is missing a dependency.

**Comment by Rubyj** [comment]
This error only comes about when updating a working application that has django-auth-ldap from 1.4 to 1.7

**Comment by jdufresne** [comment]
I'm not familiar with `autobahn`, but I'm guessing `autobahn` does not properly declare its dependency on `cryptography` (or it is optional) and this only happened to work because it relied on the transient dependencies  of other packages. These packages may have since dropped these dependencies.

**Comment by Rubyj** [comment]
@jdufresne you are correct. Thanks for the tip.

https://github.com/crossbario/autobahn-python/issues/1205
