### ISSUE TITLE
Support for multiple LDAP servers (as fallback / high availability ...)

### ISSUE THREAD

**Issue by mpibpc-mroose** [django-auth-ldap/django-auth-ldap#143]
At the moment `AUTH_LDAP_SERVER_URI` is a string containing the URI for only one particular LDAP server.

In terms of preventing a single point of failure when this server goes down one may want to give a list of URI's like this

```
AUTH_LDAP_SERVER_URI = [
    "ldaps://ldap1.example.com:636",
    "ldaps://ldap2.example.com:636",
    "ldaps://ldap3.example.com:636",
]
```
where the AuthenticationBackend tries to authenticate against each of the URIs given in  `AUTH_LDAP_SERVER_URI` until success (or final fail).

Possible problems may be the sum-up of timeouts.

**Comment by Ecno92** [comment]
If you want to implement this yourself you can assign a callable to `AUTH_LDAP_SERVER_URI` with your own fallback mechanism to check the uri before connecting. ([link](https://django-auth-ldap.readthedocs.io/en/latest/authentication.html#server-config))
However it would be nice if we can get production grade experience with some fallback mechanisms and check whether they can become part of this library.

Is anyone already having a good example which takes care of this?

**Comment by mpibpc-mroose** [comment]
In the meantime I thought the issue in deep. I decided to implement a more sustainable solution on the server side. You can easily make your LDAP servers highly available using a combination of HAProxy and keepalived. So the issue is solved for all applications at once ;-)
