### ISSUE TITLE
Cannot authenticate in Active Directory 

### ISSUE THREAD

**Issue by detininroman** [django-auth-ldap/django-auth-ldap#144]
Hello. I got stuck with your library usage. I am trying to authenticate in AD with your backend in a way described [here](https://docs.djangoproject.com/en/2.2/topics/auth/default/#topic-authorization). 

![Screenshot 2019-07-05 at 17 59 57](https://user-images.githubusercontent.com/25865133/60730943-f3ea6100-9f4e-11e9-8208-2c7a388de2df.png)

Unfortunately, `authenticate(..)` always returns `None`.
Here is my `settings.py`. Hope you can help me!
```python 
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "django_auth_ldap.backend.LDAPBackend",
]

AUTH_LDAP_SERVER_URI = "ldap://server.com"
AUTH_LDAP_BIND_DN = "name.surname@domain.com"
AUTH_LDAP_BIND_PASSWORD = "password"
AUTH_LDAP_USER_SEARCH = LDAPSearch("OU=someOU,DC=someDC,DC=someDC,DC=someDC", ldap.SCOPE_SUBTREE, "(uid=%(user)s)")
AUTH_LDAP_USER_ATTR_MAP = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}
```

**Comment by mattboston** [comment]
Did you manage to get this working with AD?

**Comment by detininroman** [comment]
Yes, I did. There was problem with LDAPSearch, my looking up for users was wrong.
