### ISSUE TITLE
Installation via Pipenv

### ISSUE THREAD

**Issue by jursed** [django-auth-ldap/django-auth-ldap#176]
Hello,

I tried installing this module via Pipenv, but during the GCC building phase of `LDAPObject.o`, the process fails. The following is an excerpt from the Pipenv stack trace (the full trace is unreadable):

```
"  building '_ldap' extension",
'  creating build/temp.linux-x86_64-3.7',
'  creating build/temp.linux-x86_64-3.7/Modules',
'  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall  -g -fdebug-prefix-map=/build/python3.7-WA8NgD/python3.7-3.7.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIB LDAP_R -DLDAPMODULE_VERSION=3.2.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/include/python3.7m -I/home/xxxxxx/.local/share/virtualenvs/xxxxxx-vxG78si7 /include/python3.7m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.7/Modules/LDAPObject.o',
'  In file included from Modules/LDAPObject.c:3:0:',
'  Modules/common.h:9:10: fatal error: Python.h: No such file or directory',
'   #include "Python.h"', '            ^~~~~~~~~~',
'  compilation terminated.',
"  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1",
'  ----------------------------------------',
'  ERROR: Failed building wheel for python-ldap',
'    ERROR: Command errored out with exit status 1:',
```

I admit that I do not grasp the packaging and building concerns for Python modules which have external C dependencies. (So, I do not understand the above.)

I'm using Ubuntu Server 18.04 and Python 3.7.5. The OS-provided package (`apt install python-ldap`) installs fine, however, it is incompatible with the Pipenv Python interpreter. When I try to "force" the import via `sys.path.append("path/to/OS/installed/packages")`, I get the following stack trace:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-d1ac9892a452> in <module>
----> 1 import ldap

/usr/lib/python3/dist-packages/ldap/__init__.py in <module>
     18   _trace_stack_limit = None
     19 
---> 20 import _ldap
     21 assert _ldap.__version__==__version__, \
     22        ImportError('ldap %s and _ldap %s version mismatch!' % (__version__,_ldap.__version__))

ModuleNotFoundError: No module named '_ldap'
```

Any ideas?

**Comment by jdufresne** [comment]
> fatal error: Python.h: No such file or directory

This suggests you do not have the Python headers installed. Can you try to install them and try again? I don't use Ubuntu, but probably one of the following command should do it:

```
apt-get install python-dev
apt-get install python3-dev
```

**Comment by jursed** [comment]
Thank you for the suggestion. I do, but the Pipenv environment prevents me from accessing it. The root of it is probably the fact that Pipenv expects a Python wheel, rather than having the client compile C code locally. Tough luck for me, I'll have to try out django-python3-ldap instead.
