### ISSUE TITLE
Custom user model with extra fields

### ISSUE THREAD

**Issue by guanxudong** [django-auth-ldap/django-auth-ldap#18]
Hi Guys,
    It seems like get_or_build_user() can not work well with custom user model. 
    It only create new user with `username` field ?  If my model need extra required fields, how can I do with it?
    Here is my custom user model below,
```python
    class CustomUser(AbstractUser):
        # extra fields
        company = models.ForeignKey(Company, on_delete=models.CASCADE)
```

**Comment by jdufresne** [comment]
Normally, for simple attributes, you can use [`AUTH_LDAP_USER_ATTR_MAP`](https://django-auth-ldap.readthedocs.io/en/latest/users.html#easy-attributes). This may not work for your case though. For more complex cases, you can either use the signal [`django_auth_ldap.backend.populate_user`](https://django-auth-ldap.readthedocs.io/en/latest/reference.html#django_auth_ldap.backend.populate_user) or override `get_or_build_user()` in a custom backend.

When `CustomUser` is being created by LDAP authentication, how do you know what value of `company` to use? Whatever logic decides that will need to be implemented in the solutions above.

Does that help? If you have any suggestions as to how to improve or clear up the documentation for such cases, those suggestions are welcome.

**Comment by guanxudong** [comment]
@jdufresne Thank you for reply:)
Because our company has more than one subsidiaries, so we have more than one LDAP.
Now we want to build a platform for all them. We can known which company he belongs to, depending on which LDAP server he connects to.
It seems I have to override `get_or_build_user()`, but thank you all the same!
