### ISSUE TITLE
AUTH_LDAP_START_TLS throws fatal error when talking to ldaps://

### ISSUE THREAD

**Issue by dragonpaw** [django-auth-ldap/django-auth-ldap#182]
If one sets the following:

```python
AUTH_LDAP_START_TLS = True
AUTH_LDAP_SERVER_URI = "ldaps://..."
```

Then one receives:

`Caught LDAPError while authenticating foo: PROTOCOL_ERROR({'desc': 'Protocol error', 'info': 'Connection already over TLS'})`

Which seems a little odd for a switch designed to encourage encryption use to throw a fatal when encryption is in use. (I feel like this should be silently ignored within the library, since the goal is already achieved.)

FYI: I'm using foxpass.com to test this, which only does ldaps.

**Comment by tyler-8** [comment]
Start TLS is a [standardized](https://tools.ietf.org/html/rfc2830) extension of LDAP, whereas "LDAPS" is kind of an 'unofficial' protocol. The two are entirely incompatible with each other as they are different protocols.

**Comment by jdufresne** [comment]
I agree. You don't need to use start TLS with `ldaps://`. Closing.
