### ISSUE TITLE
Support escape argument in LDAPSearchUnion.execute

### ISSUE THREAD

**Issue by Natureshadow** [django-auth-ldap/django-auth-ldap#186]
In the AlekSIS project, we have been relying on the `escape` keyword argument to `LDAPSearch.execute`. Now, we want to also support the `LDAPSearchUnion` for some utility code, but it does not support the `escape` keyword argument. It should accept this argument and pass it on to `search._begin`.

**Comment by jdufresne** [comment]
Thanks for the report and PR. Release in 2.2.0:  https://pypi.org/project/django-auth-ldap/2.2.0/
