### ISSUE TITLE
Can't authenticate with LDAP after moving user to another OU

### ISSUE THREAD

**Issue by sergeykorablin** [django-auth-ldap/django-auth-ldap#19]
Hi! 
I have setup LDAP auth in zulip with django_auth_ldap, it work fine, but after moving user to another organization unit (OU) he can't login.
My settings:
```
AUTH_LDAP_SERVER_URI = "ldap://domain.ru"

AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_REFERRALS: 0,
}
AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=MainDepartment,dc=domain,dc=ru",
ldap.SCOPE_SUBTREE, "(&(objectclass=person)(objectclass=user)(mail=%(user)s))")
```

User has been moved from
ou=**SubDepartment1**,ou=MainDepartment,dc=domain,dc=ru
to
ou=**SubDepartment2**,ou=MainDepartment,dc=domain,dc=ru

I don't understand why this makes a problem. Both DN must match the ldap search filter.

```
./manage.py shell
from django_auth_ldap.backend import LDAPBackend
ldapobj = LDAPBackend()
user = ldapobj.populate_user('username@domain.ru')

2018-04-11 18:22:48.193 ERR  [django_auth_ldap] search_s('cn=fname lname,ou=subdepartment1,ou=maindepartment,dc=domain,dc=ru', 0, '(objectClass=*)') raised NO_SUCH_OBJECT(
{'info': "0000208D: NameErr: DSID-03100238, 
 problem 2001 (NO_OBJECT), 
 data 0, 
 best match of:\n\t'OU=SubDepartment1,OU=MainDepartment,DC=domain,DC=ru'\n",
 'matched': 'OU=SubDepartment1,OU=MainDepartment,DC=domain,DC=ru', 
'desc': 'No such object'},)
```

**Comment by jdufresne** [comment]
Searched DNs are cached when a user login. The relevant code is here:

https://github.com/django-auth-ldap/django-auth-ldap/blob/f07854293216b0a80629a56425d2dfc03b5e1b45/django_auth_ldap/backend.py#L522-L526

So, the old DN (`ou=SubDepartment1,ou=MainDepartment,dc=domain,dc=ru`) is cached and used for the next login attempt. As the DN is no longer correct, the bind fails.

I admit, this isn't well documented and can be confusing. The easiest workaround is to set `AUTH_LDAP_GROUP_CACHE_TIMEOUT` to 0. (Keep in mind, this will disable caching if you rely on it.)

I'm open to improvements in this area -- either docs or code -- if you'd like to make a proposal or open a PR.

**Comment by sergeykorablin** [comment]
@jdufresne thank you very much for your help!

**Comment by timabbott** [comment]
@sergeykorablin thanks for the reply!  Some discussion is on https://github.com/zulip/zulip/issues/9057.  Do you know whether `AUTH_LDAP_CACHE_GROUPS` is relevant to this, or we just need to toggle set `AUTH_LDAP_GROUP_CACHE_TIMEOUT=0` in the Zulip configuration for this module?  I don't think the caching is particularly important.

**Comment by timabbott** [comment]
Great, thanks for the help @jdufresne!
