### ISSUE TITLE
Docs at https://django-auth-ldap.readthedocs.io/en/latest/ point to wrong repo

### ISSUE THREAD

**Issue by takeontom** [django-auth-ldap/django-auth-ldap#22]
Hi guys,

Noticed that your docs at https://django-auth-ldap.readthedocs.io/en/latest/ links to your (dead) Bitbucket repo, rather than this Github repo.

The correct URL is in `docs/source/index.rst`, so I guess the readthedocs site is just out of date?

![image](https://user-images.githubusercontent.com/423709/38916588-eb7fa060-42df-11e8-9ff7-4b5d168c1422.png)

**Comment by jdufresne** [comment]
Thanks for pointing this out. I should try to get a new release out soon with the updated repo. I'll try to make this a priority.

**Comment by jdufresne** [comment]
I have made a new release. Docs and PyPI should be updated:

- https://django-auth-ldap.readthedocs.io/en/latest/
- https://pypi.org/project/django-auth-ldap/

Thanks!

**Comment by takeontom** [comment]
Awesome :+1:
