### ISSUE TITLE
No active account found with the given credentials

### ISSUE THREAD

**Issue by zhaijingrong** [django-auth-ldap/django-auth-ldap#247]
I use it with the Django Restframework. But, sometimes I get a HTTP 401 error. sometimes I can get a jwt token. I do not know which problem cause that.
Is there anybody can help me.
![image](https://user-images.githubusercontent.com/24467223/116390587-cb80d480-a850-11eb-99c8-5d6778ff187f.png)
![image](https://user-images.githubusercontent.com/24467223/116390586-cb80d480-a850-11eb-9db1-1fcda9e29330.png)
![image](https://user-images.githubusercontent.com/24467223/116390609-cfacf200-a850-11eb-8872-d5e4b1e6b18d.png)

**Comment by francoisfreitag** [comment]
Hard to tell where the issue comes from without the code, authentication scheme, etc.
Issues on this project are meant for actual issues of the django auth backend integration with LDAP servers, not authentication in general. Perhaps you’ll get better luck on StackOverflow?

**Comment by zhaijingrong** [comment]
@francoisfreitag Thanks. The picture present my Django settings.
![image](https://user-images.githubusercontent.com/24467223/116490344-b4ca9400-a8c9-11eb-8c46-3bbdde833689.png)
I also try other way to fix it . Thanks again.
