### ISSUE TITLE
Multiple ldap config using ldapsearch not authentication if not found in first config

### ISSUE THREAD

**Issue by why-pengo** [django-auth-ldap/django-auth-ldap#254]
Hey,

Thanks for django-auth-ldap. I have a setup where I have two ldap config using different prefixes. I'm not able to use direct binding. I can use one or the other just fine to auth users, but not both. I have both in AUTHENTICATION_BACKENDS but it never makes it to the second backend if the user is not found in the first. Don't know if this is a bug or I'm missing some configuration.

Thanks for any help,
Jon

**Comment by francoisfreitag** [comment]
Hi @why-pengo,

If I follow correctly, `LDAPBackend` returns `None` when the user authentication was not successful, which should cause Django to continue to the next authentication backend.

IDK why the second backend would not be called. Could you share a minimal project or test to reproduce the issue? Perhaps enable debug logging in your project to get more information about what `django-auth-ldap` is doing?

**Comment by why-pengo** [comment]
Thank you for the reply @francoisfreitag,

I have it working now, I believe the issue was I had AUTH_LDAP_1_CACHE_TIMEOUT = 3600. I changed it to 0.
A comment from backend.py:
```bash
Populates self._user_dn with the distinguished name of our user.

        This will either construct the DN from a template in
        AUTH_LDAP_USER_DN_TEMPLATE or connect to the server and search for it.
        If we have to search, we'll cache the DN.
```
Says that if searching it will cache the DN. I'm using search and DN is different for each ldapbackend config. Let me know if you need more details.

**Comment by why-pengo** [comment]
I'm closing. Thank you
