### ISSUE TITLE
Use authentication for further LDAP access?

### ISSUE THREAD

**Issue by JensRestemeier** [django-auth-ldap/django-auth-ldap#268]
I want to allow a user to modify records like telephone numbers after authentication. This is possible through python-ldap or django-ldapdb.
The question is, how do I authenticate with the LDAP server with the credentials used to sign into Django? django-ldapdb seems to require specifying an admin account, while I'd like to limit permissions to what a user signing into the server would have.

Or is the correct solution to write changes into the Django user object, and then query for the password again when clicking "save" (or equivalent) before applying them to the LDAP server?

**Comment by stevecj** [comment]
That's an interesting question. We'd rather not store the user's password in plain text in the Django backend, but if we don't, then how do we run a query as the user unless we keep re-prompting the user for their password?

**Comment by stevecj** [comment]
Would this help? https://ldapwiki.com/wiki/Get%20Effective%20Rights%20Control

**Comment by francoisfreitag** [comment]
`django-auth-ldap` only offers to authenticate users against an LDAP. It’s not really meant to manage an LDAP. The following are just ideas to facilitate your use case, but not officially supported.

The user input (username and password) is available from the request post data and can be saved in a request-specific cache, to be reused when establishing a connection to the LDAP. I would recommend making a fresh connection to the LDAP to modify it, using [python-ldap](https://www.python-ldap.org/) directly.

If you want to reuse the connection from `django-auth-ldap`, it is probably accessible on the `_LDAPUser` (`ldap_user` property on the `user` object). Something like:
```python
modifications = []  # Your modifications.
modlist = ldap.modlist.modifyModlist(*args)
ldap_connection = request.user.ldap_user.connection
connection.modify(dn, modlist)
```
