### ISSUE TITLE
Blacklist a particular username from being queried via LDAP

### ISSUE THREAD

**Issue by johnthagen** [django-auth-ldap/django-auth-ldap#269]
In our deployment we have a statically configured `service-account` Django user and the remaining users authenticate via LDAP.

When we enabled logging for `django-auth-ldap` we noticed a lot of failed LDAP requests for this statically configured user:

```
search_s('cn=users,dc=example,dc=com', 2, '(uid=%(user)s)') returned 0 objects: 
Authentication failed for service-account: failed to map the username to a DN.
```

Is it possible to blacklist/filter a username so that the extra LDAP queries for these statically configured users aren't polled each time?

**Comment by francoisfreitag** [comment]
Can you insert the authentication backend for service-account before the LDAP auth backend, so that the service-account isn’t passed to the LDAP backend?
https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#authentication-backends

**Comment by johnthagen** [comment]
@francoisfreitag That works, thanks!

```py
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "django_auth_ldap.backend.LDAPBackend",
]
```

I originally ordered them with LDAP first because that is how it is prescribed in the docs:

https://django-auth-ldap.readthedocs.io/en/latest/install.html

Are there any drawbacks to putting `ModelBackend` first? Given LDAP performs I/O it seems like it would generally be better to perform `ModelBackend` checks first? Would you accept a PR to rearrange them in the docs, or add a note that says that it's okay to order them in either order?

**Comment by johnthagen** [comment]
> Happy to take in a bit of doc to precises that. 🙂

#270
