### ISSUE TITLE
Cannot find auth-ldap.txt referenced in backend.py

### ISSUE THREAD

**Issue by EHJ-52n** [django-auth-ldap/django-auth-ldap#274]
I am currently trying to set-up an django app using LDAP authentication.
As it is not working, I am looking for documentation and support.
During this process, I found a reference in `backend.py` to a file call `auth-ldap.txt` and it is not in the repository.

https://github.com/django-auth-ldap/django-auth-ldap/blob/3015de994cf09603df6777f89a9aeca8b1cf5e87/django_auth_ldap/backend.py#L28

Is there any successor of this documentation?

Please update the reference to point to something useful.

**Comment by francoisfreitag** [comment]
Are you looking for https://django-auth-ldap.readthedocs.io/en/latest/?

**Comment by EHJ-52n** [comment]
I cannot tell you, because I am newbie user of this project.

If readthedocs.io is the successor of the document, I would recommend to link it in the file. If you cannot keep the documentation next to the code, keep at least the/a link next to it.
