### ISSUE TITLE
Handling additional unresolved-reference search results

### ISSUE THREAD

**Issue by stevecj** [django-auth-ldap/django-auth-ldap#284]
I know this is really asking for the package to deal with a problem that arguably lies elsewhere, but I'm asking for it anyway. If it is agreed that this is a feature and not a misfeature, then I am definitely interested in writing an implementation.

Our application is failing to authenticate users in their AD even though other applications are having no such problem. After quite a lot of debugging, we finally figured out that our search was returning multiple results. It is returning 1 normal result and several unresolved reference results (AD part is `None` and data part is an array containing an LDAP URL string).

Neither we nor the customer knows why that is happening, but since ours is the only app having a problem with it, the perception is that it's our fault.

I have worked around the problem by copying the django-auth-ldap code into our project and patching `backend._LDAPUser._search_for_user_dn` to optionally (depending on a new setting value) iterate over the results and keep only those that have DN values.

Is this something that we can add to the official package?

**Comment by stevecj** [comment]
Since I have had a reply to #285 but not to this one, I am wondering if what I wrote was confusing. Please let me know if I need to provide more details.

I would like to submit a PR for this, but only if I have some feedback that the addition would likely be accepted.

**Comment by francoisfreitag** [comment]
The reasoning is clear. This issue requires more thinking than #285 and I am only getting to it now.

I wonder if the search terms could be more precise, in order to exclude the unwanted results and keep a single result?
I’m wary of implementing a behavior that skips some search results, although I’m failing to see how an empty DN could be useful to authenticate a user.

As an aside, my preference would be to raise an exception when there are multiple results (probably an `AuthenticationFailed`), interrupting the authentication and explaining why the authentication failed. The current behavior of returning `None` makes debugging needlessly harder. However, there’s backward compatibility to think about... It probably needs a deprecation period and major version bump. I may give that a shot in the next weeks.

**Comment by francoisfreitag** [comment]
Looking into your issue more, perhaps the library could offer a way to subclass `LDAPSearch`. That would allow you to hook into `LDAPSearch._process_results()` and discard unwanted results?

https://github.com/django-auth-ldap/django-auth-ldap/blob/ac7f1cd19321ced29a4d1f18484f423686fb6078/django_auth_ldap/config.py#L224-L246

**Comment by stevecj** [comment]
Actually, now I'm confused. The release of our software in which the customer was seeing the issue was using django-auth-ldap v2.4.0, and in that version and newer, the `_process_results` function includes `results = [r for r in results if r[0] is not None]` which filters out un-followed references.

I wrote unit tests for the patch that I added to our copy/paste of the 2.4.0 code (patched in `_LDAPUser#_search_for_user_dn`) and there should have been a test failure if those were filtered out without the option we added to turn on the additional filtering.

I'll do some debugging in there to see if I can get more detail about what's happening.

**Comment by stevecj** [comment]
OK. I see how I got those test results. I was using a test double for `search` in my unit tests.

That leaves me with a mystery. Why do the cases where a low-level search using python-ldap returns one good result, plus unresolved references fail to authenticate? I guess that's my mystery to solve though. Wish me luck.

**Comment by stevecj** [comment]
I apologize. It seems that this entire issue was moot to begin with. It is simply a fact that AD returns several un-followed references in the result for a user search, and that's presumably why you already have `results = [r for r in results if r[0] is not None]` in the `_process_results` code.

Everything I have asked for here would be redundant since that line is in the code already.

Maybe it would still be worth adding a hook so folks can add client-side filtering if they want? Maybe that's a solution in search of a problem though, in which case, we should simply close this issue.

**Comment by stevecj** [comment]
@francoisfreitag What do you think? Add a hook, so the flexibility is there, or close this?

**Comment by francoisfreitag** [comment]
Thanks for the ping. I’m closing it until we have an actual use case. It will be easier to find a satisfactory interface and add tests when we know what we are trying to accomplish.
