### ISSUE TITLE
[Questions] Set User as "is_active"

### ISSUE THREAD

**Issue by CharlotteAndre** [django-auth-ldap/django-auth-ldap#297]
Hi, it's my first time manipulating ldap auth, so maybe my question is stupid but I tried to use AUTH_LDAP_USER_FLAGS_BY_GROUP to set my user with is "is_active" status, the problem is that I have NO GROUPS in my LDAP, and it's seems i have to specify a groups... 
Is their a way to set all ldap user as active ?

**Comment by francoisfreitag** [comment]
Hi!
`is_active` defaults to `True` with Django. Assuming you have a mechanism in place that sets `is_active` to `False`, then I would hook into https://django-auth-ldap.readthedocs.io/en/master/reference.html#django_auth_ldap.backend.LDAPBackend.get_or_build_user and set `is_active` to `True` there.

**Comment by CharlotteAndre** [comment]
Well, I got a signal function setting user create via my app as inactive... So if I understand I need to write another signal function specifically for my LDAPuser, am I write ? 

Thanks for the quick answer :)

**Comment by francoisfreitag** [comment]
You probably don’t need a signal, you can extend the `get_or_build_user()` method in your LDAPBackend subclass.
