### ISSUE TITLE
NO_SUCH_OBJECT while using AUTH_LDAP_REQUIRE_GROUP

### ISSUE THREAD

**Issue by tparsa** [django-auth-ldap/django-auth-ldap#302]
Hello,

I tested Django auth LDAP with a simple project (version 4.0.0).
I get an error like below:
`WARNING:django_auth_ldap:Caught LDAPError while authenticating parsa: NO_SUCH_OBJECT({'msgtype': 111, 'msgid': 5, 'result': 32, 'desc': 'No such object', 'ctrls': [], 'matched': 'dc=example,dc=com'})`
When I commented this [condition](https://github.com/django-auth-ldap/django-auth-ldap/blob/master/django_auth_ldap/backend.py#L915) and the following line, everything is ok.
What should I do?
P.S: The group that I am specifying in AUTH_LDAP_REQUIRE_GROUP does not exist when I create the group in LDAP everything is fine but when I remove it the error comes back.

**Comment by tparsa** [comment]
I have opened a pr #303.

**Comment by francoisfreitag** [comment]
I’m failing to understand the use case? The group specified as `AUTH_LDAP_REQUIRE_GROUP` does not exist, that looks like a configuration issue?
Why demote the exception to a warning? Users won’t be able to authenticate as long as the group does not exist in the LDAP.

**Comment by tparsa** [comment]
Sorry for not so clear message from my side.

Let's say we have a AUTH_LDAP_REQUIRE_GROUP = LDAPGroupQuery('cn=team-one,dc=example,dc=com') | LDAPGroupQuery('cn=team-two,dc=example,dc=come')
In this case, if team-one does not exist and the user is a member of team-two, the user can not log in.
Now another example, let's say we are using AUTH_LDAP_USER_FLAGS_BY_GROUP, and one of the groups used in the flags does not exist or is removed by accident, then the whole authentication system will break.

Note on the warning the actual behavior of the library right now is to log a warning and not let the user log in in any of the above situations.
There won't be any unhandled exception.

Now in the pr:
The user still can't log in if they don't pass the required group condition, but they can log in if they pass condition(s) even if part of the condition is problematic.
In AUTH_LDAP_USER_FLAGS_BY_GROUP user should be able to use the system partially even if some of dn's are wrong.

**Comment by francoisfreitag** [comment]
Thanks for the explanation, I understand better. These examples would make great test case to document and verify the PR.

You’re right, the library will just emit warnings, the exception is caught at a higher level and turned into a warning.

**Comment by tparsa** [comment]
Should I put my comment in the pr as well?

**Comment by francoisfreitag** [comment]
I don’t think that’s necessary. Interested developers can trace back to the issue, and tests should capture the use case.

**Comment by francoisfreitag** [comment]
Solved with #303, thanks!
