### ISSUE TITLE
INVALID_CREDENTIALS

### ISSUE THREAD

**Issue by wanghuigithub** [django-auth-ldap/django-auth-ldap#314]
[MainThread:140289669228352][task_id:django_auth_ldap][backend.py:368][WARNING]- Caught LDAPError while authenticating LDAPADAS: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839'})

i guess the problem is ssl check
so i want to know how to close ssl check. 
thank you

**Comment by francoisfreitag** [comment]
I think the invalid credentials error comes from invalid username and password used when binding to the LDAP server.
Either the LDAP server is not setup for anonymous bind, or the credentials specified (probably with BIND_DN and BIND_PASSWORD settings) are incorrect.

**Comment by Levaitis** [comment]
I ran into this error a couple times, before I finally figured out, what setting to use in my config.

You could try debugging it with the ldapsearch command (this helped me):
```
> ldapsearch -LLL -x -h YOUR.IP.HERE:389 -D "CN=admin,CN=Users,DC=example,DC=com" -b "DC=example,DC=com" cn=admin -W

> Enter LDAP Password: AUTH_LDAP_BIND_PASSWORD
```

Where the contents of the -D flag maps to the AUTH_LDAP_BIND_DN setting and my AUTH_LDAP_USER_SEARCH is as follows: 
`AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "DC=example,DC=com", ldap.SCOPE_SUBTREE, "(CN=%(user)s)"
)`
