### ISSUE TITLE
Issues with slapd in combination with Ubuntu22.04 and Python3.10

### ISSUE THREAD

**Issue by Dizzard92** [django-auth-ldap/django-auth-ldap#321]
We are facing issues with our LDAP Unit Tests on Ubuntu22.04 and Python3.10.
Curently we are running a Django 4.1.1 application with python3.9 on Ubuntu20.04 and are in the process of upgrading to Ubuntu22.04 and Python3.10. OpenLDAP / slapd version is 2.5.13

Our pytest setup was created similiar to django-auth-ldap tests. We are using a slimmed down version of tests.ldif file and using a slapd ldap server on localhost for testing ldap accesses. We didnt do any changes to our code while upgrading to Ubuntu22.04 and Python3.10. 

You can see the error in the slapd log output which I will post at the bottom of this issue. It seems that our call of "authenticate(username="alice", password="password")" failed while executing our LDAP Search which we defined in the pytest fixture. We get following error message: "Authentication failed for alice: failed to map the username to a DN."
If I add `settings.AUTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s,ou=people,o=test"` to our fixture I get the message `DEBUG    django_auth_ldap:backend.py:823 Binding as uid=alice,ou=people,o=test` but the user which is checked in our custom Django class `class ApplicationPermission(BasePermission)` is None.

Currently I'm clueless because I'm unsure whether the problems are due to the django-auth-ldap implementation or because of the OpenLDAP version which is used.

So my first question is if the django-auth-ldap unittests did run on Ubuntu22.04?

Second question:
Does anyone of you also have problems with django 4.1.1, Python3.10, Ubuntu22.04 and slapd or can give a hint what I can try to fix the problem?

Here are some code snippets for further insight:

**Pytest fixture which we are using in our unittests:**

    @pytest.fixture
    def ldap(settings):
      settings.AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
          "ou=groups,o=test", ldap_import.SCOPE_SUBTREE, "(objectClass=groupOfNames)"
      )
  
      settings.AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr="cn")
      settings.AUTH_LDAP_USER_SEARCH = LDAPSearch(
          "ou=people,o=test", ldap_import.SCOPE_SUBTREE, "(uid=%(user)s)"
      )
  
      settings.AUTHENTICATION_BACKENDS = [
          "django_auth_ldap.backend.LDAPBackend",
          "django.contrib.auth.backends.ModelBackend",
      ]
  
      here = os.path.dirname(__file__)
      server = slapdtest.SlapdObject()
      server.suffix = "o=test"
      server.openldap_schema_files = [
          "core.ldif",
          "cosine.ldif",
          "inetorgperson.ldif",
          "nis.ldif",
      ]
      server.start()
      with open(os.path.join(here, "test_resources/ldap_test.ldif")) as fp:
          ldif = fp.read()
      server.slapadd(ldif)
      settings.AUTH_LDAP_SERVER_URI = server.ldap_uri
      return server

**slapd log output:**

[...]
63231904.105e6a18 0x7f6be8ab0640 <<< dnPrettyNormal: <ou=people,o=test>, <ou=people,o=test>
63231904.105fbbfc 0x7f6be8ab0640 SRCH "ou=people,o=test" 2 0    0 0 0
63231904.10612488 0x7f6be8ab0640 begin get_filter
63231904.10624020 0x7f6be8ab0640 EQUALITY
63231904.1063b8b0 0x7f6be8ab0640 ber_scanf fmt ({mm}) ber:
63231904.1064dc7c 0x7f6be8ab0640 ber_dump: buf=0x7f6be0103370 ptr=0x7f6be0103396 end=0x7f6be01033a6 len=16
63231904.10656728 0x7f6be8ab0640   0000:  a3 0c 04 03 75 69 64 04  05 61 6c 69 63 65 30 00   ....uid..alice0.  
63231904.1066b970 0x7f6be8ab0640 end get_filter 0
63231904.1067d7c4 0x7f6be8ab0640     filter: (uid=alice)
63231904.10685b04 0x7f6be8ab0640 ber_scanf fmt ({M}}) ber:
63231904.1069fb6c 0x7f6be8ab0640 ber_dump: buf=0x7f6be0103370 ptr=0x7f6be01033a4 end=0x7f6be01033a6 len=2
63231904.106b36a8 0x7f6be8ab0640   0000:  00 00                                              ..                
63231904.106cd7d8 0x7f6be8ab0640     attrs: 
63231904.106e39c0 0x7f6be8ab0640 conn=1001 op=1 SRCH base="ou=people,o=test" scope=2 deref=0 filter="(uid=alice)"
63231904.107896e0 0x7f6be8ab0640 ==> limits_get: conn=1001 op=1 self="[anonymous]" this="ou=people,o=test"
63231904.107c6068 0x7f6be8ab0640 => mdb_search
63231904.107dde0c 0x7f6be8ab0640 mdb_opinfo_get: err Invalid argument(22)
[...]
ERROR    django_auth_ldap:config.py:155 search_s('ou=people,o=test', 2, '(uid=alice)') raised OTHER({'msgtype': 101, 'msgid': 2, 'result': 80, 'desc': 'Other (e.g., implementation specific) error', 'ctrls': [], 'info': 'internal error'})
DEBUG    django_auth_ldap:config.py:243 search_s('ou=people,o=test', 2, '(uid=%(user)s)') returned 0 objects: 
DEBUG    django_auth_ldap:backend.py:347 Authentication failed for alice: failed to map the username to a DN.
 
_

**pytest log -> Binding as ' ' no user is named here.:**
------------------------------ Captured log call -------------------------------
DEBUG    django_auth_ldap:backend.py:823 Binding as 
DEBUG    django_auth_ldap:config.py:147 Invoking search_s('ou=people,o=test', 2, '(uid=alice)')
ERROR    django_auth_ldap:config.py:155 search_s('ou=people,o=test', 2, '(uid=alice)') raised OTHER({'msgtype': 101, 'msgid': 2, 'result': 80, 'desc': 'Other (e.g., implementation specific) error', 'ctrls': [], 'info': 'internal error'})
DEBUG    django_auth_ldap:config.py:243 search_s('ou=people,o=test', 2, '(uid=%(user)s)') returned 0 objects: 
DEBUG    django_auth_ldap:backend.py:347 Authentication failed for alice: failed to map the username to a DN.

**Comment by francoisfreitag** [comment]
> So my first question is if the django-auth-ldap unittests did run on Ubuntu22.04?

Last run was on 20.04. https://github.com/django-auth-ldap/django-auth-ldap/actions/runs/2868304693/jobs/4550387896
The CI action specified `ubuntu-latest`, but it seems GitHub actions remain at 20.04 LTS for now https://github.com/django-auth-ldap/django-auth-ldap/actions/runs/2867676880/jobs/4942230573.

> Does anyone of you also have problems with django 4.1.1, Python3.10, Ubuntu22.04 and slapd or can give a hint what I can try to fix the problem?

I’m not using Ubuntu. Did you try to query the LDAP manually with `ldapsearch` to see if the user is indeed present and try narrowing down the issue?

**Comment by Dizzard92** [comment]
Thx for response! As I can see in the actions/runner-images repository README.md the tag "ubuntu-latest" points to ubuntu-20.04 and only the tag ubuntu-22.04 uses the newest image. Maybe you can give it a try and run your GitHub actions with ubuntu-22.04?

I'll try to run the LDAP search manually, as you recommended. Maybe I'll get new insights.

**Comment by francoisfreitag** [comment]
Tests are passing on Ubuntu 22.04. https://github.com/django-auth-ldap/django-auth-ldap/actions/runs/3067050325/jobs/4952918861

**Comment by francoisfreitag** [comment]
#322 was the experiment PR for that issue.
