### ISSUE TITLE
Should have a proper changelog

### ISSUE THREAD

**Issue by Natureshadow** [django-auth-ldap/django-auth-ldap#326]
The changelog should be continued in `docs/changes.rst` instead of only in GitHub releases.

GitHub releases are not accessible. They are not bundled with the source tarball, they are not readable without loading a ton of non-free JavaScript, and they are only accessible under GitHub's exclusive terms of use.

More on changelogs in general: https://keepachangelog.com/en/1.0.0/

**Comment by francoisfreitag** [comment]
Thanks for the suggestion, but I’m not interested.

The GitHub release provides a neat automation for creating the changelog for each release. It avoids an item in the checklist when reviewing a PR, that is often forgotten despite said checklist. It highlights new contributors automatically.
Marking the release on GitHub is a pretty good practice regardless of changelogs, at least to provide a tarball of the source at a given point in time.

> They are not bundled with the source tarball

Can you detail how that is an issue ? The person interested in the history of changes will be much better served by git than a text document in a package that contains a single version of the code.

> they are not readable without loading a ton of non-free JavaScript, and they are only accessible under GitHub's exclusive terms of use.

While I sympathize with that issue, GitHub is also not accessible without enabling that proprietary JavaScript, but is required if you want to contribute to this project (or many other open-source projects).
If you really want to access the release information without running the proprietary JavaScript, you can use the [hub](https://github.com/github/hub) tool with `hub release show X.X.X`.

Besides, a changelog is mostly useful for a few months after issuing a release. Changelog entries for unsupported versions aren’t as precise as the git history, and I seriously doubt many people read entries past their current version. Loosing the changelog for old entries does not look like a big deal to me.

**Comment by Natureshadow** [comment]
> Thanks for the suggestion, but I’m not interested.

Thank you for the honest statement that you are not interested in properly enabling users and downstreams.
