### ISSUE TITLE
ldap connection failure

### ISSUE THREAD

**Issue by nomatterfine** [django-auth-ldap/django-auth-ldap#327]
`[MainThread:140349678393152][task_id:django_auth_ldap][backend.py:358][WARNING]- Caught LDAPError while authenticating liangxuch: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839'})`

What does this mistake mean？
thanks！

**Comment by francoisfreitag** [comment]
Looks like you use invalid credentials (from `INVALID_CREDENTIALS`) in the log.
