### ISSUE TITLE
Installation on Windows Machine not working

### ISSUE THREAD

**Issue by Ntonsite** [django-auth-ldap/django-auth-ldap#359]
I am having hard time getting this package to work within my windows PC, installation endins with errors.
" pip install django-auth-ldap
Collecting django-auth-ldap
  Using cached django_auth_ldap-4.6.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: Django>=3.2 in c:\users\ntonsite.mwamlima\projects\fullstack\rttweb\venv\lib\site-packages (from django-auth-ldap) (4
.2.7)
Collecting python-ldap>=3.1 (from django-auth-ldap)
  Using cached python-ldap-3.4.4.tar.gz (377 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: asgiref<4,>=3.6.0 in c:\users\ntonsite.mwamlima\projects\fullstack\rttweb\venv\lib\site-packages (from Django>=3.2->d
jango-auth-ldap) (3.7.2)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\ntonsite.mwamlima\projects\fullstack\rttweb\venv\lib\site-packages (from Django>=3.2->dja
ngo-auth-ldap) (0.4.4)
Requirement already satisfied: tzdata in c:\users\ntonsite.mwamlima\projects\fullstack\rttweb\venv\lib\site-packages (from Django>=3.2->django-auth-
ldap) (2023.3)
Requirement already satisfied: pyasn1>=0.3.7 in c:\users\ntonsite.mwamlima\projects\fullstack\rttweb\venv\lib\site-packages (from python-ldap>=3.1->
django-auth-ldap) (0.4.8)
Collecting pyasn1-modules>=0.1.5 (from python-ldap>=3.1->django-auth-ldap)
  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Using cached django_auth_ldap-4.6.0-py3-none-any.whl (20 kB)
Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for python-ldap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-312
      copying Lib\ldapurl.py -> build\lib.win-amd64-cpython-312
      copying Lib\ldif.py -> build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\async.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\asyncsearch.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\cidict.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\compat.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\constants.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\dn.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\filter.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\functions.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\ldapobject.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\logger.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\modlist.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\pkginfo.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\resiter.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\sasl.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\syncrepl.py -> build\lib.win-amd64-cpython-312\ldap
      copying Lib\ldap\__init__.py -> build\lib.win-amd64-cpython-312\ldap
      creating build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\deref.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\libldap.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\openldap.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\pagedresults.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\ppolicy.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\psearch.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\pwdpolicy.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\readentry.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\sessiontrack.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\simple.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\sss.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\vlv.py -> build\lib.win-amd64-cpython-312\ldap\controls
      copying Lib\ldap\controls\__init__.py -> build\lib.win-amd64-cpython-312\ldap\controls
      creating build\lib.win-amd64-cpython-312\ldap\extop
      copying Lib\ldap\extop\dds.py -> build\lib.win-amd64-cpython-312\ldap\extop
      copying Lib\ldap\extop\passwd.py -> build\lib.win-amd64-cpython-312\ldap\extop
      copying Lib\ldap\extop\__init__.py -> build\lib.win-amd64-cpython-312\ldap\extop
      creating build\lib.win-amd64-cpython-312\ldap\schema
      copying Lib\ldap\schema\models.py -> build\lib.win-amd64-cpython-312\ldap\schema
      copying Lib\ldap\schema\subentry.py -> build\lib.win-amd64-cpython-312\ldap\schema
      copying Lib\ldap\schema\tokenizer.py -> build\lib.win-amd64-cpython-312\ldap\schema
      copying Lib\ldap\schema\__init__.py -> build\lib.win-amd64-cpython-312\ldap\schema
      creating build\lib.win-amd64-cpython-312\slapdtest
      copying Lib\slapdtest\_slapdtest.py -> build\lib.win-amd64-cpython-312\slapdtest
      copying Lib\slapdtest\__init__.py -> build\lib.win-amd64-cpython-312\slapdtest
      running egg_info
      writing Lib\python_ldap.egg-info\PKG-INFO
      writing dependency_links to Lib\python_ldap.egg-info\dependency_links.txt
      writing requirements to Lib\python_ldap.egg-info\requires.txt
      writing top-level names to Lib\python_ldap.egg-info\top_level.txt
      reading manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'Doc\.build'
      adding license file 'LICENCE'
      writing manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
      creating build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\README -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\ca.conf -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\ca.pem -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\client.conf -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\client.key -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\client.pem -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\gencerts.sh -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\gennssdb.sh -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\server.conf -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\server.key -> build\lib.win-amd64-cpython-312\slapdtest\certs
      copying Lib\slapdtest\certs\server.pem -> build\lib.win-amd64-cpython-312\slapdtest\certs
      running build_ext
      building '_ldap' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\Modules
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD
 -DHAVE_SASL -DHAVE_TLS -DLDAPMODULE_VERSION=3.4.4 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -IC:\User
s\ntonsite.mwamlima\projects\fullstack\rttweb\venv\include -IC:\Users\ntonsite.mwamlima\AppData\Local\Programs\Python\Python312\include -IC:\Users\n
tonsite.mwamlima\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.3313
0\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.
0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0
\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\c
ppwinrt" /TcModules/LDAPObject.c /Fobuild\temp.win-amd64-cpython-312\Release\Modules/LDAPObject.obj
      LDAPObject.c
      C:\Users\ntonsite.mwamlima\AppData\Local\Temp\pip-install-62rlioka\python-ldap_ff1d4ec4e9c44b8ca976babe8db567f0\Modules\common.h(15): fatal er
ror C1083: Cannot open include file: 'lber.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed w
ith exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-ldap
Failed

Please assist!.

**Comment by francoisfreitag** [comment]
You are lacking headers for LDAP (`lber.h`). You may have luck following https://www.python-ldap.org/en/python-ldap-3.4.3/installing.html.
