### ISSUE TITLE
Return different LDAP_SERVER_URI based on the username

### ISSUE THREAD

**Issue by hetsch** [django-auth-ldap/django-auth-ldap#58]
I have a usecase where my server uri depends on the username. Currently, users should login with their email addresses which are either `foo@uni-bar.com` or `foo@edu.uni-bar.com`. The difference is the domains is, that one are students (edu) and the others are employees. Both have different LDAP endpoints.

According to the documentation, `settings.SERVER_URI` can be a callable, returning a dynically generated URI. My question would be if you think it would make sense to pass the `request` object to `_LDAPUser` (see: https://github.com/django-auth-ldap/django-auth-ldap/blob/master/django_auth_ldap/backend.py#L148) and to invoke the `setting.SERVER_URI` callback with the request object (https://github.com/django-auth-ldap/django-auth-ldap/blob/master/django_auth_ldap/backend.py#L806). People could then calculate different SERVER_URIs based on the current request.

Do you think this might be worth implementing, or is there any other way I'm not aware of?

**Comment by jdufresne** [comment]
That sounds like an a solid improvement to me. Are you interested in creating a PR with tests? There might be some concern with backwards compatibility, so some care would need to be taken to continue to support a `SERVER_URI` without a request object.

**Comment by hetsch** [comment]
All right. I'll have a look tomorrow and try to come up with (hopefully) something useful. Thank's for your feedback!

**Comment by hetsch** [comment]
Long time since I posted this issue. Finally I came up with an idea how to implement this. See #72.
