### ISSUE TITLE
Automatically set password on Django side on successful LDAP authentication

### ISSUE THREAD

**Issue by malefice** [django-auth-ldap/django-auth-ldap#75]
According to the docs, an unusable password is set for any user created by the LDAPBackend. While I agree that this should be the default behavior, I think that we should also add an option that automatically sets/updates/mirrors the password of the user object on the Django side if the LDAP credentials are valid.

One scenario where this is especially useful is if one has absolutely no control/visibility over anything involving the LDAP server, like in the case of a 3rd party vendor integrating with a client's LDAP server. If for some reason the client's LDAP server is inaccessible, with this option, the existing users can still use the Django application with the same LDAP credentials w/ no additional steps from a sysadmin. At least this way, you have some form of graceful degradation.

Anyway, I took a quick look at the code, and I can think of two ways to add this option. Both options involve passing the password to the `_get_or_create_user` method of `_LDAPUser` as shown [here](https://github.com/django-auth-ldap/django-auth-ldap/blob/5c3fbdc9058bdaffb40127dd77d0bf692ecec379/django_auth_ldap/backend.py#L348-L350). From there, we can then create a new setting to run the automatic behavior. If it is more desirable from a design perspective to let the developers handle that explicitly, we can also opt to pass the password to the `django_auth_ldap.backend.populate_user` signal instead.

This is all assuming I got things right. If the password is already an attribute of another argument of the `populate_user` signal, then perhaps we can note that in the documentation instead. In any case, I will be glad to create a PR for this. So.. thoughts on this one?

**Comment by jdufresne** [comment]
I'm not sure about this. This would mean the LDAP server isn't a single source of truth. It seems like it would hurt the security of the Django site.

A user could be intentionally removed from the LDAP directory, but would still be allowed to login to the Django site. If this user were removed for negative reasons, they may take advantage of still being allowed to login to do harm.

A user could have their password compromised. Maybe they changed it in the LDAP directory, but it would remain the old password in Django. If a malicious user had obtained the compromised password, they would be able to use it to login to the Django site.

**Comment by malefice** [comment]
Seems like there is currently no general interest in this, so I think this issue can be closed if the repo maintainers want to. However, I will be leaving some code snippets for the benefit of anyone who might (unfortunately) need this. If the behavior will not be a built-in option, then another way to do this is to make use of some of the hooks and (undocumented) parts of the library.

Subclass the LDAPBackend, use the `default_settings` dictionary class attribute to define a key that will control the behavior, and use the `authenticate_ldap_user` hook to implement the logic. It will look something like this.

```
from django_auth_ldap.backend import LDAPBackend

class CustomLDAPBackend(LDAPBackend):
    default_settings = {
        "MIRROR_CREDENTIALS": False,
    }

    def authenticate_ldap_user(self, ldap_user, password):
        user = ldap_user.authenticate(password)
        if self.settings.MIRROR_CREDENTIALS and user:
            user.set_password(password)
            # Do something else like refresh how long the local copy
            # will be valid if you allow mirroring of credentials. This 
            # will mitigate security issues.
            user.save()
        return user
```

Then change your settings.py.
```
# ...
AUTHENTICATION_BACKENDS = [
#   ....
    'dotted.path.to.CustomLDAPBackend',
#   ....
]

AUTH_LDAP_MIRROR_CREDENTIALS = True
```

The `AUTH_LDAP_MIRROR_CREDENTIALS` will be unnecessary if the default value of the `MIRROR_CREDENTIALS` key in the subclass is `True`, but since this is potentially dangerous behavior without the proper mitigation, I recommend to keep the default at `False` and explicitly enable it when needed.

**Comment by jdufresne** [comment]
@malefice I think that is a good compromise. django-auth-ldap has enough hooks so someone can do this if required without actively promoting behavior that may be less secure. Thanks!

**Comment by malefice** [comment]
Fortunately I had some time earlier today, so I went through the source code more thoroughly. That is when I found out about the `default_settings` class attribute and was able to come up and test this alternative.

The `default_settings` class attribute though is only mentioned once in the change log. Instead of building in a behavior you are not comfortable adding into the library, perhaps we can improve on the documentation, and put an example like this to demonstrate the possibilities. That is assuming the `default_settings` class attribute is considered stable and not just internal.

If you think that is a good idea, just inform me, and I will try to write some docs.

**Comment by jdufresne** [comment]
That sounds great! PRs improving the docs is most welcome. Although, I think we should find an example that doesn't actively promote system state that may be less secure. Can we use an example other than storing the password that conveys the same idea? Thanks.

**Comment by malefice** [comment]
Yes, of course. I will think of a generic example, and it will be more like "you can define your own custom settings here, and use those settings in any of the subclass methods by accessing self.settings".
