### ISSUE TITLE
Emit a signal if a user was successfully authenticated

### ISSUE THREAD

**Issue by hetsch** [django-auth-ldap/django-auth-ldap#84]
As far as I could read from the documentation, the only signal that gets emitted on the first successful authentication is the `populate_user` signal. What I would need is a signal on every successful authentication, not depending on any population of user data. My current workaround is to set `AUTH_LDAP_ALWAYS_UPDATE_USER` to `True` what triggers the `populate_user` signal on every successful authentication. If I don't want to populate the data on every authentication attempt, I currently don't see any way for getting notified (outside of the function that invokes the backend) if authentication succeeded. Do I miss something and if not, what do you think about implementing such a signal? Thank's again!

**Comment by jdufresne** [comment]
Can you use the Django signal `user_logged_in`?

https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#django.contrib.auth.signals.user_logged_in

I don't think django-auth-ldap needs anything specific as this is already builtin behavior.

**Comment by jdufresne** [comment]
Closing as there has been no response. If you still feel this is useful, please provide the details to show how `user_logged_in` isn't meeting your needs.
