### ISSUE TITLE
Manage password properties

### ISSUE THREAD

**Issue by magmax** [django-auth-ldap/django-auth-ldap#94]
AFAIK, it is not possible to manage password properties such as expired password grace period, password must be changed (to force the change on first logon) or last login information.

ApacheDS allows to manage this, and I think it would be a good idea to have access to those properties, despite django-auth-ldap does not manage them.

**Comment by jdufresne** [comment]
Thanks for the feature suggestion @magmax Are you interested in creating a pull request to add it?

**Comment by jdufresne** [comment]
Thanks for following up
