### ISSUE TITLE
How to implement custom GroupType?

### ISSUE THREAD

**Issue by mbleonardo** [django-auth-ldap/django-auth-ldap#96]
Hi!

I'm trying to use an application that uses django-auth-ldap (Ansible AWX). We have a very specific "group" implementation (we use eDirectory with roles). In case, all the users' groups are in its own attribute called securityEquals - and the "list" of all the groups are in different tree, and don't have a list of members. 

But, before using the attribute itself, I tried to test using: [EdirRoleGroupType.txt](https://github.com/django-auth-ldap/django-auth-ldap/files/2416675/EdirRoleGroupType.txt)

But when checking group membership I get the following error:

`DEBUG    django_auth_ldap cn=leo,ou=users,ou=accounts,o=myorg is not a member of cn=grp-g-adm,cn=network groups,cn=level10,cn=roledefs,cn=roleconfig,cn=appconfig,cn=userapplication,cn=driverset,ou=system,o=myorg`
 
How this method should return group data?

Thank you!

**Comment by jdufresne** [comment]
You can take a look at the various group implementations here:

https://github.com/django-auth-ldap/django-auth-ldap/blob/master/django_auth_ldap/config.py

If one doesn't fit your needs, consider implementing a custom one.

**Comment by jdufresne** [comment]
If there is nothing else to resolve, I'll close this. If you still feel there is a missing feature or the docs could be more clear, please state so and I'll reopen.
