### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by kennethmensah** [django-auth-ldap/django-auth-ldap#99]
I keep getting 'cannot include basetsd.h' error

**Comment by jdufresne** [comment]
Please provide the full command and output used to install.

**Comment by kennethmensah** [comment]
Hi @jdufresne I used pip install django-auth-ldap on a Windows machine

**Comment by kennethmensah** [comment]
Cannot open include file: 'basetsd.h': No such file or directory

That is the error message

**Comment by jdufresne** [comment]
No response. If you provide the details requested, I'll reopen.
